# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

env:
  
  AWS_AMI_REGION: ${{ secrets.AWS_AMI_REGION }}
  CD_APP_NAME: ${{ secrets.CD_APP_NAME }}
  D_APP_DEPLOY_GNAME: ${{ secrets.D_APP_DEPLOY_GNAME }}
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        npm install 
        sudo apt-get install awscli -y
        sudo apt-get install less -y

    - name: Zip and upload to s3
      run: |
        cp ../*.json .
        cp ../*.md .
        zip -r webapp .
        ls -a
        aws s3 cp webapp.zip s3://${s3_bucket_name}
        echo 'upload to s3 done'

    - name: deploy
      run: |
          output=$(aws deploy create-deployment \
          --application-name webapp \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name webapp-group \
          --description "CSYE6255 - CodeDeploy" \
          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},key=webapp.zip,bundleType=zip \
          --region us-east-1 \
          --output json)
          echo $output
          dId=$(echo $output | jq -r '.deploymentId')
          aws deploy wait deployment-successful --deployment-id $dId